### ISSUE TITLE
Создать новый экран "Повторение"

### ISSUE THREAD

**Issue by IvanShalimov** [DimaMaligon/EnglishWords#12]
Создать второй экран
Упражнение "Повторение"
Берет случайные слова из словаря и выводит на экран.  Дается четыре варианта на выбор, после выбора слова, переходим к следующему слову. Сверху счетчик угаданных слов и показанных. Вход на экран доступен если в словаре 4 или более слов.
UI:
Текстовая метка со словом-загадкой. 4 варианта ответа(форма вольная). Счетчик правильных и всех попыток. Выход с экрана либо по нажатию клавиши "UP", либо по нажатию кнопки "Back"(В тулбаре)

**Comment by DimaMaligon** [comment]
Сделано
