### ISSUE TITLE
Дублируется toolbar + не работает кнопка "Назад"

### ISSUE THREAD

**Issue by IvanShalimov** [DimaMaligon/EnglishWords#2]
![image](https://user-images.githubusercontent.com/16368990/230972987-1d6db6d1-8814-4811-8ee2-26b3b1a878d6.png)

_Originally posted by @IvanShalimov in https://github.com/DimaMaligon/EnglishWords/pull/1#discussion_r1161988497_

**Comment by IvanShalimov** [comment]
Чтобы TopBar не дублировался наследуй для LetterActivity не от AppCompatActivity, а от ComponentActivity

**Comment by DimaMaligon** [comment]
Да я переделаю навигацию и думаю, все поправиться.

**Comment by DimaMaligon** [comment]
https://github.com/DimaMaligon/EnglishWords/pull/6 add the  new pull request for backbutton
