### ISSUE TITLE
После нажатия "Save" не перерисовывается список

### ISSUE THREAD

**Issue by IvanShalimov** [DimaMaligon/EnglishWords#3]
сделал, что прорисовывается, но как-то через раз работает, пока не пойму, что делать((

_Originally posted by @DimaMaligon in https://github.com/DimaMaligon/EnglishWords/pull/1#discussion_r1164291638_

**Comment by DimaMaligon** [comment]
будет решена в задаче https://github.com/DimaMaligon/EnglishWords/issues/9

**Comment by DimaMaligon** [comment]
сделано, кнопка сохранить  теперь перерисовавает спиоск после нажатия. Исправилось с помощью вынесение методов по работе с базой данных в модел вью.
