### ISSUE TITLE
Редизайн приложения

### ISSUE THREAD

**Issue by IvanShalimov** [DimaMaligon/EnglishWords#4]
1. Переделать архитектуру на сингл активити
2. Внедрить Navigation
3. Изменить дизайн(спросить у Вани как)

**Comment by DimaMaligon** [comment]
https://github.com/DimaMaligon/EnglishWords/pull/5   добавил пулл реквест на первые два пункта. Последний спрошу в понедельник.

**Comment by DimaMaligon** [comment]
3 пункт будет решаться в задаче https://github.com/DimaMaligon/EnglishWords/issues/8
