### ISSUE TITLE
Изменить дизайн приложения

### ISSUE THREAD

**Issue by DimaMaligon** [DimaMaligon/EnglishWords#8]
сделать привлекательный ui

**Comment by IvanShalimov** [comment]
![photo_2023-04-26_15-45-37](https://user-images.githubusercontent.com/16368990/234565377-c04c2d08-5780-46e2-9495-104494580c17.jpg)
![photo_2023-04-26_15-44-56](https://user-images.githubusercontent.com/16368990/234565514-4ba0f77e-cd46-4252-9028-aef6a8b74153.jpg)
![photo_2023-04-26_15-44-57](https://user-images.githubusercontent.com/16368990/234565586-3ecd0a84-a0b5-45b3-89d7-c513e26de865.jpg)
![photo_2023-04-26_15-44-58](https://user-images.githubusercontent.com/16368990/234565645-6fdec740-b4ca-4e55-8b36-4d75848028c3.jpg)
![photo_2023-04-26_15-44-58 (2)](https://user-images.githubusercontent.com/16368990/234565654-1ec618d1-ddfe-4849-8748-b08a27b40371.jpg)
![photo_2023-04-26_15-44-59](https://user-images.githubusercontent.com/16368990/234565666-4a2a9f8a-56df-4f53-949b-293fdff99231.jpg)

**Comment by IvanShalimov** [comment]
Выполнено
